repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.0.1
  hooks:
  - id: shellcheck
  - id: shfmt
